<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_mwm_contact',
    'title' => 'MWM Contacto',
    'fields' => array(
        array(
            'key' => 'field_mwm_contact_title',
            'label' => 'Título',
            'name' => 'title',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array(
            'key' => 'field_mwm_contact_description',
            'label' => 'Descripción',
            'name' => 'description',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'rows' => 4,
        ),
        array(
            'key' => 'field_mwm_contact_shortcode',
            'label' => 'Shortcode',
            'name' => 'shortcode',
            'type' => 'text',
            'instructions' => 'Ingrese el shortcode del formulario de contacto',
            'required' => 0,
        ),
        array(
            'key' => 'field_mwm_contact_phone_info_group',
            'label' => 'Información de teléfono',
            'name' => 'phone_info',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_mwm_contact_phone_info_icon',
                    'label' => 'Icono',
                    'name' => 'icon',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_mwm_contact_phone_info_title',
                    'label' => 'Título',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_mwm_contact_phone_info_phone',
                    'label' => 'Teléfono',
                    'name' => 'phone',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_mwm_contact_info_group',
            'label' => 'Información de correo electrónico',
            'name' => 'contact_info',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_mwm_contact_email_info_icon',
                    'label' => 'Icono',
                    'name' => 'icon',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_mwm_contact_email_info_title',
                    'label' => 'Título',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_mwm_contact_email_info_email',
                    'label' => 'Correo electrónico',
                    'name' => 'email',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_mwm_contact_map_group',
            'label' => 'Información del Mapa',
            'name' => 'map_info',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_mwm_contact_map_image',
                    'label' => 'Imagen del Mapa',
                    'name' => 'map_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_mwm_contact_map_link',
                    'label' => 'Enlace del Mapa',
                    'name' => 'map_link',
                    'type' => 'text',
                    'instructions' => 'Ingrese el enlace de Google Maps',
                    'required' => 0,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/mwm-contact',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

endif; 